import pokemons from "../../images/pokemons.png";
import pets from "../../images/pets.png";
import arsenal from "../../images/arsenal.png";
import games from "../../images/games.png";
import chat from "../../images/chat.png";
import jobs from "../../images/jobs.png";
import converter from "../../images/converter.png";
import marvel from "../../images/marvel.png";
import movies from "../../images/movies.png";
import baloons from "../../images/baloons.png";
import employers from "../../images/employers.png";
import shop from "../../images/shop.png";
import heroes from "../../images/heroes.png";
import blog from "../../images/blog.png";
import news from "../../images/news.png";
import live_chat from "../../images/live_chat.png";
import rick_morty from "../../images/rick-morty.png";
import space from "../../images/space.png";

export const projects = [
    {
        index: 16,
        name: "Rick-Morty",
        description: "",
        img: rick_morty,
        pageSpeed: 99,
        deploy: "https://rick-morty-extended.vercel.app/",
        github: "https://github.com/Denys1994q/rick-morty-extended",
        technologies: ["typescript", "angular", "angular-router", "angular-material", "rick-morty-api", "sass"],
    },
    {
        index: 15,
        name: "Live-Chat",
        description: "",
        img: live_chat,
        pageSpeed: 100,
        deploy: "https://live-chat-theta.vercel.app/",
        github: "https://github.com/Denys1994q/chat_frontend",
        githubBackend: "https://github.com/Denys1994q/chat_backend",
        technologies: [
            "websockets",
            "node",
            "express",
            "express-validator",
            "mongoDb",
            "mongoose",
            "jwt",
            "multer",
            "cloudinary",
            "react",
            "typescript",
            "redux",
            "redux-toolkit",
            "material-design",
            "git",
        ],
    },
    {
        index: 14,
        name: "Blog",
        description: "",
        img: blog,
        pageSpeed: 98,
        deploy: "https://blog-frontend1994.vercel.app/",
        github: "https://github.com/Denys1994q/blog_frontend",
        githubBackend: "https://github.com/Denys1994q/blog_backend",
        technologies: [
            "node",
            "express",
            "express-validator",
            "mongoDb",
            "mongoose",
            "jwt",
            "multer",
            "cloudinary",
            "react",
            "typescript",
            "redux",
            "redux-toolkit",
            "material-design",
            "git",
        ],
    },
    {
        index: 10,
        name: "Pokemons",
        description: "",
        img: pokemons,
        pageSpeed: 97,
        deploy: "https://pokemons-redux1.vercel.app/",
        github: "https://github.com/Denys1994q/Pokemons-Redux",
        technologies: [
            "react",
            "redux",
            "redux-toolkit",
            "sass",
            "grid",
            "chart-js",
            "react-select",
            "react-lazy-load",
            "react-spinners",
            "react-transition-group",
            "react-loading-skeleton",
            "react-font-awesome",
            "git",
        ],
    },
    {
        index: 9,
        name: "FC Arsenal",
        img: arsenal,
        pageSpeed: 95,
        deploy: "https://arsenal1994q.vercel.app/",
        github: "https://github.com/Denys1994q/Arsenal-React",
        technologies: [
            "next",
            "react",
            "redux-toolkit",
            "sass",
            "grid",
            "git",
            "fetch",
            "omdb-api",
            "weather-api",
            "marvel-api",
            "react-image-magnify",
        ],
    },
    {
        index: 12,
        name: "Games",
        img: games,
        pageSpeed: 100,
        deploy: "https://games-plum.vercel.app/",
        github: "https://github.com/Denys1994q/games",
        technologies: [
            "next",
            "react",
            "typescript",
            "freetogame-api",
            "sass-modules",
            "classnames",
            "react-spinners",
            "react-font-awesome",
            "git",
            "fetch",
        ],
    },
    {
        index: 17,
        name: "Space App",
        description: "",
        img: space,
        pageSpeed: 90,
        deploy: "https://space-x-beta.vercel.app/",
        github: "https://github.com/Denys1994q/spaceX",
        technologies: ["typescript", "react", "styled-components", "graphQl", "Apollo", "Atomic design", "Recoil"],
    },
    {
        index: 13,
        name: "News",
        description: "",
        img: news,
        pageSpeed: 98,
        deploy: "https://news-zeta-nine.vercel.app/",
        github: "https://github.com/Denys1994q/news",
        technologies: ["react", "typescript", "redux", "redux-toolkit", "material-design", "sass", "git"],
    },
    {
        index: 8,
        name: "Pets",
        description: "",
        img: pets,
        pageSpeed: 92,
        deploy: "https://cats-page-eosin.vercel.app/",
        github: "https://github.com/Denys1994q/test-task-CatsAPI",
        technologies: ["react", "react-router-dom", "sass", "flex", "grid", "git", "post", "fetch"],
    },
    // {
    //     index: 11,
    //     name: "Jobs",
    //     description: "",
    //     img: jobs,
    //     pageSpeed: 100,
    //     deploy: "https://jobs-tawny.vercel.app/",
    //     github: "https://github.com/Denys1994q/jobs",
    //     technologies: ["next", "react", "redux", "redux-toolkit", "sass", "git", "fetch"],
    // },
    {
        name: "Chat",
        description: "",
        img: chat,
        pageSpeed: 98,
        deploy: "https://chat-react-henna.vercel.app/",
        github: "https://github.com/Denys1994q/chat_React",
        technologies: ["react", "sass", "git", "fetch", "chuck-norris-jokes-api", "react-google-login", "gapi-script"],
    },
    {
        index: 5,
        name: "Marvel",
        description: "",
        img: marvel,
        deploy: "",
        github: "https://github.com/Denys1994q/Project_React_marvelComics",
        technologies: ["react", "sass", "react-transition-group", "git", "fetch", "helmet", "marvel-api"],
    },
    // {
    //     index: 4,
    //     name: "Movies API",
    //     description: "",
    //     img: movies,
    //     deploy: "",
    //     github: "https://github.com/Denys1994q/React-Movies-API",
    //     technologies: ["react", "materialize-css", "flex", "git", "fetch", "omdb-api"],
    // },
    {
        index: 7,
        name: "currency converter",
        img: converter,
        deploy: "",
        github: "https://github.com/Denys1994q/currency_converter_REACT",
        technologies: ["react", "flex", "git", "fetch", "currencies-api"],
    },
    // {
    //     index: 2,
    //     name: "magic heroes",
    //     description: "",
    //     img: heroes,
    //     deploy: "",
    //     github: "https://github.com/Denys1994q/heroes-redux",
    //     technologies: ["react", "redux", "git"],
    // },
    // {
    //     index: 3,
    //     name: "react shop",
    //     description: "",
    //     img: shop,
    //     deploy: "",
    //     github: "https://github.com/Denys1994q/React-Shop",
    //     technologies: ["react", "flex", "git", "fetch", "currencies-api"],
    // },
    // {
    //     index: 1,
    //     name: "employers",
    //     description: "",
    //     img: employers,
    //     deploy: "",
    //     github: "https://github.com/Denys1994q/Project_React_employers",
    //     technologies: ["react", "git"],
    // },
    // {
    //     index: 6,
    //     name: "Balloons",
    //     description: "",
    //     img: baloons,
    //     deploy: "",
    //     github: "https://github.com/Denys1994q/HTML-CSS_Ballons",
    //     technologies: ["html", "sass", "flex", "git"],
    // },
];
